openapi: 3.0.0
info:
  title: Users Management API
  version: 1.0.0
servers:
  - url: 'http://api.usersmanagement.com/v1'
paths:
  /users:
    get:
      summary: Retrieve all Users
      responses:
        '200':
          description: A list of Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{id}:
    get:
      summary: Retrieve a specific User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the User
      responses:
        '200':
          description: A specific User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update a specific User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Updated User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete a specific User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the User
      responses:
        '204':
          description: User deleted successfully

  /permissions:
    get:
      summary: Retrieve all Permissions
      responses:
        '200':
          description: A list of Permissions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permission'
    post:
      summary: Create a new Permission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Permission'
      responses:
        '201':
          description: Created Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'

  /permissions/{id}:
    get:
      summary: Retrieve a specific Permission
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the Permission
      responses:
        '200':
          description: A specific Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
    put:
      summary: Update a specific Permission
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the Permission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Permission'
      responses:
        '200':
          description: Updated Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
    delete:
      summary: Delete a specific Permission
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the Permission
      responses:
        '204':
          description: Permission deleted successfully

  /user-permissions:
    get:
      summary: Retrieve all UserPermissions
      responses:
        '200':
          description: A list of UserPermissions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPermission'
    post:
      summary: Create a new UserPermission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPermission'
      responses:
        '201':
          description: Created UserPermission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermission'

  /user-permissions/{id}:
    get:
      summary: Retrieve a specific UserPermission
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the UserPermission
      responses:
        '200':
          description: A specific UserPermission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermission'
    put:
      summary: Update a specific UserPermission
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the UserPermission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPermission'
      responses:
        '200':
          description: Updated UserPermission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermission'
    delete:
      summary: Delete a specific UserPermission
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the UserPermission
      responses:
        '204':
          description: UserPermission deleted successfully

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          maxLength: 50
        email:
          type: string
          maxLength: 100
        hashed_password:
          type: string
          maxLength: 255
        full_name:
          type: string
          maxLength: 100
        status:
          type: string
          maxLength: 50
          enum:
            - active
            - inactive
            - disabled
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Permission:
      type: object
      properties:
        id:
          type: integer
          format: int64
        permission_name:
          type: string
          maxLength: 100
        description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    UserPermission:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        permission_id:
          type: integer
          format: int64
        assigned_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time