openapi: 3.0.0
info:
  title: Vulnerability Management API
  version: 1.0.0
servers:
  - url: 'http://api.vulnerabilitymanagement.com/v1'
paths:
  /vulnerability-entry-managers:
    get:
      summary: Retrieve all VulnerabilityEntryManagers
      responses:
        '200':
          description: A list of VulnerabilityEntryManagers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VulnerabilityEntryManager'
    post:
      summary: Create a new VulnerabilityEntryManager
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilityEntryManager'
      responses:
        '201':
          description: Created VulnerabilityEntryManager
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityEntryManager'

  /vulnerability-entry-managers/{id}:
    get:
      summary: Retrieve a specific VulnerabilityEntryManager
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityEntryManager
      responses:
        '200':
          description: A specific VulnerabilityEntryManager
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityEntryManager'
    put:
      summary: Update a specific VulnerabilityEntryManager
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityEntryManager
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilityEntryManager'
      responses:
        '200':
          description: Updated VulnerabilityEntryManager
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityEntryManager'
    delete:
      summary: Delete a specific VulnerabilityEntryManager
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityEntryManager
      responses:
        '204':
          description: VulnerabilityEntryManager deleted successfully

  /vulnerability-databases:
    get:
      summary: Retrieve all VulnerabilityDatabases
      responses:
        '200':
          description: A list of VulnerabilityDatabases
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VulnerabilityDatabase'
    post:
      summary: Create a new VulnerabilityDatabase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilityDatabase'
      responses:
        '201':
          description: Created VulnerabilityDatabase
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityDatabase'

  /vulnerability-databases/{id}:
    get:
      summary: Retrieve a specific VulnerabilityDatabase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityDatabase
      responses:
        '200':
          description: A specific VulnerabilityDatabase
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityDatabase'
    put:
      summary: Update a specific VulnerabilityDatabase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityDatabase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilityDatabase'
      responses:
        '200':
          description: Updated VulnerabilityDatabase
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityDatabase'
    delete:
      summary: Delete a specific VulnerabilityDatabase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityDatabase
      responses:
        '204':
          description: VulnerabilityDatabase deleted successfully

  /vulnerability-records:
    get:
      summary: Retrieve all VulnerabilityRecords
      responses:
        '200':
          description: A list of VulnerabilityRecords
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VulnerabilityRecord'
    post:
      summary: Create a new VulnerabilityRecord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilityRecord'
      responses:
        '201':
          description: Created VulnerabilityRecord
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityRecord'

  /vulnerability-records/{id}:
    get:
      summary: Retrieve a specific VulnerabilityRecord
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityRecord
      responses:
        '200':
          description: A specific VulnerabilityRecord
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityRecord'
    put:
      summary: Update a specific VulnerabilityRecord
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityRecord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VulnerabilityRecord'
      responses:
        '200':
          description: Updated VulnerabilityRecord
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityRecord'
    delete:
      summary: Delete a specific VulnerabilityRecord
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the VulnerabilityRecord
      responses:
        '204':
          description: VulnerabilityRecord deleted successfully

components:
  schemas:
    VulnerabilityEntryManager:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 100
        description:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    VulnerabilityDatabase:
      type: object
      properties:
        id:
          type: integer
          format: int64
        entry_manager_id:
          type: integer
          format: int64
        database_name:
          type: string
          maxLength: 100
        source_url:
          type: string
        last_updated:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    VulnerabilityRecord:
      type: object
      properties:
        id:
          type: integer
          format: int64
        vulnerability_db_id:
          type: integer
          format: int64
        vulnerability_id:
          type: string
          maxLength: 100
        description:
          type: string
        severity_level:
          type: integer
          format: int32
        status:
          type: string
          maxLength: 50
        published_at:
          type: string
          format: date-time
        last_modified:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time